Repository Dan6erbond/aPRAW, pull requests merged in 2020-07, with the labels that each got.

#65 Rework Listings
  .gitignore
  apraw/__init__.py
  apraw/models/__init__.py
  apraw/models/comment.py
  apraw/models/helpers/apraw_base.py
  apraw/models/helpers/generator.py
  apraw/models/helpers/listing.py
  apraw/models/helpers/listing_generator.py
  apraw/models/helpers/streamable.py
  apraw/models/mixins/author.py
  apraw/models/redditor.py
  apraw/models/subreddit.py
  apraw/models/subreddit_wiki.py
  apraw/reddit.py
  docs/api/index.rst
  docs/api/models/subreddit/index.rst
  docs/api/models/subreddit/subreddit_wiki.rst
  docs/api/other/index.rst
  docs/api/other/streamable.rst
  docs/index.rst
  requests/dumps/modaction.json
  tests/integration/models/test_listing_generator.py
  tests/integration/models/test_subreddit_wiki.py
Labels: enhancement

#68 Update Streamable Decorator
  apraw/models/__init__.py
  apraw/models/helpers/streamable.py
  apraw/models/redditor.py
  apraw/models/subreddit.py
  apraw/models/subreddit_wiki.py
  apraw/reddit.py
  tests/unit/models/helpers/__init__.py
  tests/unit/models/helpers/test_streamable.py
Labels: bug, enhancement

#69 Inbox Listings, kind_filter, Packages and more
  apraw/const.py
  apraw/endpoints.py
  apraw/models/__init__.py
  apraw/models/helpers/generator.py
  apraw/models/helpers/item_moderation.py
  apraw/models/helpers/listing.py
  apraw/models/mixins/author.py
  apraw/models/mixins/deletable.py
  apraw/models/mixins/hideable.py
  apraw/models/mixins/nsfwable.py
  apraw/models/mixins/savable.py
  apraw/models/mixins/spoilerable.py
  apraw/models/mixins/subreddit.py
  apraw/models/mixins/votable.py
  apraw/models/reddit/__init__.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/message.py
  apraw/models/reddit/redditor.py
  apraw/models/reddit/submission.py
  apraw/models/subreddit/__init__.py
  apraw/models/subreddit/moderation.py
  apraw/models/subreddit/modmail.py
  apraw/models/subreddit/subreddit.py
  apraw/models/subreddit/wiki.py
  apraw/models/user.py
  apraw/reddit.py
  requests/dumps/inbox.json
  requests/dumps/morechildren.json
  requests/requests.http
  tests/integration/models/test_submission.py
  tests/integration/models/test_subreddit.py
  tests/integration/test_reddit.py
Labels: endpoint, enhancement, feature

#72 Inbox Listings Tests
  apraw/models/__init__.py
  apraw/models/reddit/comment.py
  tests/integration/models/test_user.py
Labels: enhancement, tests

#73 [ENDPOINT] Replying to Submissions/Comments/Messages
  apraw/endpoints.py
  apraw/models/mixins/replyable.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/message.py
  apraw/models/reddit/submission.py
  requests/requests.http
  tests/integration/models/test_submission.py
Labels: endpoint

#74 Update Docstrings To Raw Text
  apraw/models/helpers/streamable.py
  apraw/models/reddit/redditor.py
  apraw/models/reddit/submission.py
  apraw/models/subreddit/moderation.py
  apraw/models/subreddit/subreddit.py
  apraw/models/subreddit/wiki.py
  apraw/reddit.py
Labels: documentation, enhancement

#75 [ENDPOINT] Random Subreddit Submissions
  apraw/endpoints.py
  apraw/models/subreddit/subreddit.py
  apraw/reddit.py
  tests/integration/models/test_subreddit.py
Labels: endpoint, enhancement

#77 Add support for the /api/submit endpoint
  apraw/endpoints.py
  apraw/models/reddit/submission.py
  apraw/models/subreddit/subreddit.py
  tests/integration/models/test_subreddit.py
Labels: endpoint

#80 Make aPRAWBase Lazy
  apraw/models/__init__.py
  apraw/models/helpers/apraw_base.py
  apraw/models/mixins/author.py
  apraw/models/mixins/deletable.py
  apraw/models/mixins/replyable.py
  apraw/models/mixins/subreddit.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/listing.py
  apraw/models/reddit/redditor.py
  apraw/models/reddit/submission.py
  apraw/models/subreddit/moderation.py
  apraw/models/subreddit/modmail.py
  apraw/models/subreddit/subreddit.py
  apraw/models/subreddit/wiki.py
  apraw/models/user.py
  apraw/reddit.py
  tests/integration/models/test_comment.py
  tests/integration/models/test_submission.py
  tests/integration/models/test_submission_moderation.py
Labels: enhancement, feature

#82 Reactive Comments, Fix Stream
  apraw/models/helpers/apraw_base.py
  apraw/models/helpers/streamable.py
  apraw/models/reddit/comment.py
  apraw/models/user.py
  apraw/reddit.py
  apraw/utils/__init__.py
  apraw/utils/counter.py
  requirements.txt
  setup.py
  tests/integration/models/test_comment.py
Labels: bug, enhancement, feature

#84 CommentForrest and MoreComments
  apraw/models/__init__.py
  apraw/models/helpers/comment_forrest.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/listing.py
  apraw/models/reddit/more_comments.py
  apraw/models/reddit/submission.py
  apraw/models/subreddit/subreddit.py
  apraw/models/user.py
  apraw/reddit.py
  requests/dumps/morecomments.json
  tests/integration/models/test_comment_forrest.py
  tests/integration/test_reddit.py
Labels: enhancement

#86 Refactor `CommentForrest` to `CommentForest`
  apraw/models/helpers/comment_forest.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/listing.py
  apraw/models/reddit/submission.py
Labels: enhancement

#88 Bring up @streamable decorator and create ProxyStreamable using Descriptor Protocol
  apraw/models/__init__.py
  apraw/models/helpers/streamable.py
  apraw/models/reddit/redditor.py
  apraw/models/subreddit/moderation.py
  apraw/models/subreddit/subreddit.py
  apraw/models/subreddit/wiki.py
  apraw/models/user.py
  apraw/reddit.py
  tests/unit/models/helpers/test_streamable.py
Labels: bug, enhancement

#91 Fix Return in Message Function
  apraw/reddit.py
  tests/integration/models/test_redditor.py
Labels: bug

#92 Fix Message Class Mixin Initialization
  apraw/models/reddit/message.py
  tests/integration/models/test_message.py
Labels: bug

#93 Fixed spoiler issue
  apraw/models/mixins/spoilerable.py
  tests/integration/models/test_submission_moderation.py
Labels: bug

#96 Add Support for /r/mod and /r/all Listings.
  apraw/models/subreddit/subreddit.py
  tests/integration/models/test_subreddit.py
Labels: enhancement

#97 Support for ReactivePy 2.0
  apraw/models/reddit/comment.py
Labels: enhancement

#98 Add support for Subreddit Removal Reasons
  apraw/const.py
  apraw/endpoints.py
  apraw/models/__init__.py
  apraw/models/helpers/item_moderation.py
  apraw/models/mixins/deletable.py
  apraw/models/mixins/hideable.py
  apraw/models/mixins/nsfwable.py
  apraw/models/mixins/replyable.py
  apraw/models/mixins/savable.py
  apraw/models/mixins/spoilerable.py
  apraw/models/mixins/votable.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/more_comments.py
  apraw/models/reddit/redditor.py
  apraw/models/reddit/submission.py
  apraw/models/subreddit/modmail.py
  apraw/models/subreddit/removal_reasons.py
  apraw/models/subreddit/subreddit.py
  apraw/models/subreddit/wiki.py
  apraw/models/user.py
  apraw/reddit.py
  apraw/request_handler.py
  requests/dumps/removal_reasons.json
  requests/requests.http
  tests/integration/models/test_subreddit.py
Labels: endpoint, feature

#102 Add Docpages, Update Docstrings and Typing
  apraw/__init__.py
  apraw/models/__init__.py
  apraw/models/enums/__init__.py
  apraw/models/enums/distinguishment_option.py
  apraw/models/helpers/apraw_base.py
  apraw/models/helpers/comment_forest.py
  apraw/models/helpers/generator.py
  apraw/models/helpers/item_moderation.py
  apraw/models/helpers/streamable.py
  apraw/models/mixins/link.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/listing.py
  apraw/models/reddit/message.py
  apraw/models/reddit/more_comments.py
  apraw/models/reddit/redditor.py
  apraw/models/subreddit/moderation.py
  apraw/models/subreddit/removal_reasons.py
  apraw/models/subreddit/subreddit.py
  apraw/models/subreddit/wiki.py
  apraw/models/user.py
  apraw/reddit.py
  docs/api/enums/index.rst
  docs/api/helpers/apraw_base.rst
  docs/api/helpers/comment_forest.rst
  docs/api/helpers/index.rst
  docs/api/helpers/item_moderation.rst
  docs/api/helpers/listing_generator.rst
  docs/api/helpers/streamable.rst
  docs/api/models/index.rst
  docs/api/models/listing.rst
  docs/api/models/message.rst
  docs/api/models/more_comments.rst
  docs/api/models/subreddit/index.rst
  docs/api/models/subreddit/moderation.rst
  docs/api/models/subreddit/modmail.rst
  docs/api/models/subreddit/removal_reasons.rst
  docs/api/models/subreddit/wiki.rst
  docs/getting_started/quickstart.rst
  docs/index.rst
  requests/dumps/wiki.json
  requests/dumps/wikipage_revision.json
  requirements.txt
Labels: documentation, enhancement

#104 Add Parameters to ItemModeration.remove()
  apraw/endpoints.py
  apraw/models/helpers/item_moderation.py
  apraw/models/mixins/hideable.py
  apraw/models/mixins/nsfwable.py
  apraw/models/mixins/savable.py
  apraw/models/mixins/spoilerable.py
  apraw/models/mixins/votable.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/submission.py
  apraw/models/subreddit/removal_reasons.py
Labels: endpoint, enhancement, feature

#106 Add Subreddit Settings and Support for Multireddits
  apraw/endpoints.py
  apraw/models/__init__.py
  apraw/models/mixins/subreddit.py
  apraw/models/subreddit/moderation.py
  apraw/models/subreddit/settings.py
  apraw/models/subreddit/subreddit.py
  apraw/reddit.py
  docs/api/models/subreddit/moderation.rst
  requests/dumps/subreddit_settings.json
  requests/requests.http
  tests/integration/models/test_subreddit.py
Labels: endpoint

#109 Add Support to fetch Modmail by ID
  apraw/models/subreddit/modmail.py
  apraw/models/subreddit/subreddit.py
  apraw/reddit.py
  apraw/request_handler.py
  docs/api/models/subreddit/modmail.rst
  requests/requests.http
  tests/integration/models/test_subreddit.py
Labels: endpoint, enhancement

#110 Add Support for Fetching Submissions and Comments by URL
  apraw/models/helpers/apraw_base.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/submission.py
  apraw/reddit.py
  tests/integration/test_reddit.py
Labels: enhancement, feature

#114 Add Support to Ban Users on a Subreddit
  apraw/endpoints.py
  apraw/models/__init__.py
  apraw/models/helpers/generator.py
  apraw/models/mixins/link.py
  apraw/models/mixins/redditor.py
  apraw/models/reddit/comment.py
  apraw/models/reddit/listing.py
  apraw/models/reddit/submission.py
  apraw/models/subreddit/banned.py
  apraw/models/subreddit/moderation.py
  apraw/models/subreddit/subreddit.py
  docs/api/models/subreddit/banned.rst
  docs/api/models/subreddit/index.rst
  docs/api/models/subreddit/moderation.rst
  requests/dumps/subreddit_banned.json
  requests/requests.http
  tests/integration/models/test_subreddit.py
Labels: endpoint, enhancement, feature

#115 Add Support to Mute, Archive and Reply to Modmail
  apraw/endpoints.py
  apraw/models/subreddit/modmail.py
  tests/integration/models/test_modmail.py
Labels: endpoint, enhancement, feature

#116 Add Support for Flair in PostModeration
  apraw/endpoints.py
  apraw/models/helpers/item_moderation.py
  apraw/models/reddit/submission.py
  tests/integration/models/test_submission_moderation.py
Labels: endpoint, enhancement

#118 Fix await Redditor.redditor in ModmailMessage
  apraw/models/subreddit/modmail.py
  tests/integration/models/test_comment_forest.py
  tests/integration/models/test_modmail.py
Labels: bug, enhancement

#120 Add await to Reddit.post() in ItemModeration._add_removal_reason()
  apraw/models/helpers/item_moderation.py
Labels: bug

#121 Add await to Reddit.post() in ItemModeration._add_removal_reason()
  apraw/models/helpers/item_moderation.py
Labels: bug

#123 Fix ModAction.mod()
  apraw/models/subreddit/moderation.py
  tests/integration/models/test_subreddit.py
Labels: bug, tests
